# 🗄️ SQL remind 드릴 · 미션 3개 — Student

예측 → 작성 → 실행 → 확인 순서로 강의 코드를 연습한다.

> **🖥️ 환경 설정**
>
> - **로컬**: 수업에서 안내한 FD_26 실행 환경의 커널을 선택한 뒤, 이 노트북을 practice 폴더에서 연다.
>
> - 이번 주는 Colab 병행 없이 VS Code(로컬) 단일 경로다.
>
> **⌨️ 단축키 안내**
>
> | 단축키 | 동작 |
> |--------|------|
> | `Shift + Enter` | 셀 실행 후 다음 셀 이동 |
> | `Esc → A` | 위에 셀 삽입 |
> | `Esc → B` | 아래에 셀 삽입 |
> | `Esc → DD` | 셀 삭제 |

In [3]:
# 🖥️ 환경 설정
# - VS Code에서 FD_26/.venv 커널을 선택했는지 먼저 확인한다 (실행·설치는 전부 FD_26에서).

import os
import sys
import sqlite3
import pandas as pd

print(sys.executable)
# 예상 출력: (자기 프로젝트 경로)/FD_26/.venv/bin/python3

conn = sqlite3.connect('data/market_data.db')

c:\Projects\FD_26\.venv\Scripts\python.exe

In [4]:
query= """
select * 
    from financials
"""



df=pd.read_sql(query,conn)
print(df)

      code  year  revenue  operating_profit  net_income   equity
0   005930  2024  3180000            357922      294180  3268670
1   005930  2025  3466200            499015      381432  3467567
2   000660  2024   826000            275009      225201  1023639
3   000660  2025  1007720            364837      303706  1265440
4   009150  2024    93600              7373        5984   119680
5   009150  2025    91728              8991        7191   102726
6   051910  2024   465600             18052       13467   448893
7   051910  2025   470256             32577       27965   559304
8   011170  2024   138000                 0           0   171385
9   011170  2025   131100              3851        2867   143361
10  010950  2024   357000             16693       13584   339597
11  010950  2025   367710             26932       22467   374447
12  005380  2024  1680000            232270      187051  2338136
13  005380  2025  1797600            304402      248457  2484568
14  000270  2024  1090000            157963      125681  1142554
15  000270  2025  1209900            205485      157993  1215332
16  105560  2024   226600             22193       17983   256902
17  105560  2025   237930             24781       21162   235131
18  055550  2024   214200             20180       17094   284900
19  055550  2025   222768             28016       24313   303909
20  207940  2024    46000              5891        4998    41646
21  207940  2025    54740              9127        7120    50857
22  035420  2024   107000             11621        8745   124924
23  035420  2025   117700             17534       14785   164279

In [5]:
query = """
select * from financials limit 5 """

## 🎯 조건으로 거르기 — WHERE

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [6]:
pd.read_sql(query,conn)

     code  year  revenue  operating_profit  net_income   equity
0  005930  2024  3180000            357922      294180  3268670
1  005930  2025  3466200            499015      381432  3467567
2  000660  2024   826000            275009      225201  1023639
3  000660  2025  1007720            364837      303706  1265440
4  009150  2024    93600              7373        5984   119680

In [7]:
# 📌 §300 🎯 조건으로 거르기 — WHERE cell_id=300:1
# 코드를 작성해주세요 👇
# ✍️ 힌트: WHERE 뒤에 매출과 연도를 AND로 연결한다.
query = "SELECT code, revenue FROM financials WHERE revenue > 300000 AND year = 2025"
pd.read_sql(query, conn)
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  revenue
0  005930  3466200
1  000660  1007720
2  051910   470256
3  010950   367710
4  005380  1797600
5  000270  1209900

## 📐 상위 몇 개만 — ORDER BY · LIMIT

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [8]:
# 📌 §300 📐 상위 몇 개만 — ORDER BY · LIMIT cell_id=300:2
# 코드를 작성해주세요 👇
query="""
select code,revenue from financials where year == 2025 order by revenue desc limit 5
"""
pd.read_sql(query , conn)

# ✍️ 힌트: ORDER BY revenue DESC 뒤에 LIMIT 5를 붙인다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  revenue
0  005930  3466200
1  005380  1797600
2  000270  1209900
3  000660  1007720
4  051910   470256

In [9]:
# 📌 §300 📐 상위 몇 개만 — ORDER BY · LIMIT cell_id=300:3
# 코드를 작성해주세요 👇
query="""
select code,revenue from financials where year==2025 limit 5
"""

pd.read_sql(query, conn)
# ✍️ 힌트: 정렬 없이 LIMIT만 썼을 때를 비교한다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  revenue
0  005930  3466200
1  000660  1007720
2  009150    91728
3  051910   470256
4  011170   131100

## ➕ 없는 열을 만들어 쓴다 — AS · 계산 컬럼

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [11]:
# 📌 §300 ➕ 없는 열을 만들어 쓴다 — AS · 계산 컬럼 cell_id=300:4
# 코드를 작성해주세요 👇
query="""
select code, net_income, equity, net_income/equity as roe_wrong,
round(net_income*1.0/equity,4) as roe_right 
from financials where year==2025
limit 5
"""
pd.read_sql(query,conn)
# ✍️ 힌트: 분자에 1.0을 곱해 소수 나눗셈을 만든다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  net_income   equity  roe_wrong  roe_right
0  005930      381432  3467567          0       0.11
1  000660      303706  1265440          0       0.24
2  009150        7191   102726          0       0.07
3  051910       27965   559304          0       0.05
4  011170        2867   143361          0       0.02

In [ ]:
# 📌 §300 🧭 쉬운 한 표로 먼저 묻기 — WHERE · ORDER BY · LIMIT cell_id=300:13
# 코드를 작성해주세요 👇
query =""" 
select code, revenue from financials where year==2025 and revenue>300000
order by revenue desc limit 5
"""

pd.read_sql(query,conn)
# ✍️ 힌트: financials 한 표에서 2025년 매출 300000 초과 행만 남기고, 매출 내림차순으로 5개를 고른다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  revenue
0  005930  3466200
1  005380  1797600
2  000270  1209900
3  000660  1007720
4  051910   470256

In [ ]:
query=""" 
select * from companies limit 5"""

pd.read_sql(query,conn)

     code    name sector market
0  005930    삼성전자   전기전자  KOSPI
1  000660  SK하이닉스   전기전자  KOSPI
2  009150    삼성전기   전기전자  KOSPI
3  051910    LG화학     화학  KOSPI
4  011170   롯데케미칼     화학  KOSPI

In [16]:
# 📌 §300 🔒 심화/선택 — 산업별로 묶는다 — GROUP BY · 집계 cell_id=300:5
# 코드를 작성해주세요 👇
query="""
select c.code, f.revenue, c.sector, round(avg(f.net_income*1.0/f.equity),4) as avg_roe,count(*) as cnt
from companies c join financials f on c.code=f.code
where f.year=2025
group by c.sector
order by avg_roe desc
limit 5
"""
pd.read_sql(query,conn)
# ✍️ 힌트: 앞의 집계 결과를 avg_roe 내림차순으로 정렬한다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  revenue sector  avg_roe  cnt
0  005930  3466200   전기전자    0.140    3
1  207940    54740    바이오    0.140    1
2  005380  1797600    자동차    0.115    2
3  035420   117700    서비스    0.090    1
4  105560   237930     금융    0.085    2

## 🔗 두 표를 잇는다 — JOIN

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [ ]:
# 📌 §300 🔗 두 표를 잇는다 — JOIN cell_id=300:6
# 코드를 작성해주세요 👇
query =""" 
select count(*) as n_rows
from companies c join financials f on c.code=f.code"""

pd.read_sql(query, conn)
# ✍️ 힌트: 두 표에 함께 있는 code로 ON 조건을 쓴다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

   n_rows
0      24

In [ ]:
# 📌 §300 🔗 두 표를 잇는다 — JOIN cell_id=300:7
# 코드를 작성해주세요 👇
query =""" 
select count(*) as n_rows
from companies"""

pd.read_sql(query, conn)
# ✍️ 힌트: ON이 없을 때 행 수가 어떻게 달라지는지 확인한다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

   n_rows
0      12

## 🚨 에러 읽는 법

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [ ]:
# 📌 §300 🚨 에러 읽는 법 cell_id=300:8
# 코드를 작성해주세요 👇
# ✍️ 힌트: 오류를 try/except로 받아 메시지를 출력한다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

In [ ]:
# 📌 §300 🚨 에러 읽는 법 cell_id=300:9
# 코드를 작성해주세요 👇
# ✍️ 힌트: 세 오류 쿼리를 하나씩 실행하고 메시지를 기록한다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

## ✍️ 미션 1 — 특정 업종에서 매출 상위 5개 회사

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [ ]:
# 📌 §300 🔒 심화/선택 — 미션 1 — 특정 업종에서 매출 상위 5개 회사 cell_id=300:10
# 코드를 작성해주세요 👇
query=""" 
select f.code, f.revenue from companies c
join financials f on c.code==f.code 
where c.sector="전기전자"
order by f.revenue desc limit 5
 """
pd.read_sql(query,conn)
# ✍️ 힌트: companies와 financials를 code로 잇고, WHERE로 업종을 고른 뒤 ORDER BY ... DESC LIMIT 5.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

     code  revenue
0  005930  3466200
1  005930  3180000
2  000660  1007720
3  000660   826000
4  009150    93600

## ✍️ 미션 2 — 업종별 평균 수익성과 회사 수

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [17]:
# 📌 §300 🔒 심화/선택 — 미션 2 — 업종별 평균 수익성과 회사 수 cell_id=300:11
# 코드를 작성해주세요 👇
query=""" 
select c.sector, round(avg(f.net_income*1.0/f.equity),4) as avg_roe, count(*) as n
from companies c join financials f on c.code=f.code
where f.year=2025
group by c.sector
order by avg_roe desc
limit 5
"""
pd.read_sql(query,conn)
# ✍️ 힌트: 위 GROUP BY 절에서 쓴 쿼리와 같은 모양이다. 묶은 기준(sector)과 집계값(AVG, COUNT)만 고른다.
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.

  sector  avg_roe  n
0   전기전자    0.140  3
1    바이오    0.140  1
2    자동차    0.115  2
3    서비스    0.090  1
4     금융    0.085  2

## ✍️ 미션 3 — 자유 조건 (학습자 자신의 조건)

이 예시의 실행 흐름을 먼저 예측한 뒤, 같은 질문을 노트북에서 확인한다.

[→ §300 강의노트](../notes/FD-03-300__sql-remind.md)

In [ ]:
# 📌 §300 ✍️ 미션 3 — 자유 조건 (학습자 자신의 조건) cell_id=300:12
# 코드를 작성해주세요 👇
# ✍️ 힌트: companies와 financials를 code로 잇고, 자기가 궁금한 조건 하나를 WHERE에 직접 넣는다.
#   예) "ROE가 0.1보다 큰 회사는?", "이름에 특정 글자가 들어간 회사는?"
# 예상 출력:
# 강의노트의 실행 결과와 비교한다.